version: '3.8'

volumes:
  src:

services:

  nodejs:
    build:
      context: .
    container_name: MY_NODEJS
    environment:
      NODE_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./src/:/home/app/src/
